// Code generated by MockGen. DO NOT EDIT.
// Source: aos.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	api "github.com/brittonhayes/aos/api"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockRepository) Generate(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockRepositoryMockRecorder) Generate(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRepository)(nil).Generate), ctx, name)
}

// GetAbilitiesForUnitByID mocks base method.
func (m *MockRepository) GetAbilitiesForUnitByID(ctx context.Context, id string) ([]api.Ability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAbilitiesForUnitByID", ctx, id)
	ret0, _ := ret[0].([]api.Ability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAbilitiesForUnitByID indicates an expected call of GetAbilitiesForUnitByID.
func (mr *MockRepositoryMockRecorder) GetAbilitiesForUnitByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAbilitiesForUnitByID", reflect.TypeOf((*MockRepository)(nil).GetAbilitiesForUnitByID), ctx, id)
}

// GetAllegianceByID mocks base method.
func (m *MockRepository) GetAllegianceByID(ctx context.Context, id string) (*api.Allegiance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllegianceByID", ctx, id)
	ret0, _ := ret[0].(*api.Allegiance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllegianceByID indicates an expected call of GetAllegianceByID.
func (mr *MockRepositoryMockRecorder) GetAllegianceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllegianceByID", reflect.TypeOf((*MockRepository)(nil).GetAllegianceByID), ctx, id)
}

// GetAllegiances mocks base method.
func (m *MockRepository) GetAllegiances(ctx context.Context, params *api.GetAllegiancesParams) ([]api.Allegiance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllegiances", ctx, params)
	ret0, _ := ret[0].([]api.Allegiance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllegiances indicates an expected call of GetAllegiances.
func (mr *MockRepositoryMockRecorder) GetAllegiances(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllegiances", reflect.TypeOf((*MockRepository)(nil).GetAllegiances), ctx, params)
}

// GetArmies mocks base method.
func (m *MockRepository) GetArmies(ctx context.Context) ([]api.Army, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArmies", ctx)
	ret0, _ := ret[0].([]api.Army)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArmies indicates an expected call of GetArmies.
func (mr *MockRepositoryMockRecorder) GetArmies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArmies", reflect.TypeOf((*MockRepository)(nil).GetArmies), ctx)
}

// GetArmyByID mocks base method.
func (m *MockRepository) GetArmyByID(ctx context.Context, id string) (*api.Army, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArmyByID", ctx, id)
	ret0, _ := ret[0].(*api.Army)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArmyByID indicates an expected call of GetArmyByID.
func (mr *MockRepositoryMockRecorder) GetArmyByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArmyByID", reflect.TypeOf((*MockRepository)(nil).GetArmyByID), ctx, id)
}

// GetCities mocks base method.
func (m *MockRepository) GetCities(ctx context.Context, params *api.GetCitiesParams) ([]api.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCities", ctx, params)
	ret0, _ := ret[0].([]api.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCities indicates an expected call of GetCities.
func (mr *MockRepositoryMockRecorder) GetCities(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCities", reflect.TypeOf((*MockRepository)(nil).GetCities), ctx, params)
}

// GetCityByID mocks base method.
func (m *MockRepository) GetCityByID(ctx context.Context, id string) (*api.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityByID", ctx, id)
	ret0, _ := ret[0].(*api.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityByID indicates an expected call of GetCityByID.
func (mr *MockRepositoryMockRecorder) GetCityByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityByID", reflect.TypeOf((*MockRepository)(nil).GetCityByID), ctx, id)
}

// GetGrandAllianceByID mocks base method.
func (m *MockRepository) GetGrandAllianceByID(ctx context.Context, id string) (*api.GrandAlliance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrandAllianceByID", ctx, id)
	ret0, _ := ret[0].(*api.GrandAlliance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrandAllianceByID indicates an expected call of GetGrandAllianceByID.
func (mr *MockRepositoryMockRecorder) GetGrandAllianceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrandAllianceByID", reflect.TypeOf((*MockRepository)(nil).GetGrandAllianceByID), ctx, id)
}

// GetGrandAlliances mocks base method.
func (m *MockRepository) GetGrandAlliances(ctx context.Context) ([]api.GrandAlliance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrandAlliances", ctx)
	ret0, _ := ret[0].([]api.GrandAlliance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrandAlliances indicates an expected call of GetGrandAlliances.
func (mr *MockRepositoryMockRecorder) GetGrandAlliances(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrandAlliances", reflect.TypeOf((*MockRepository)(nil).GetGrandAlliances), ctx)
}

// GetGrandStrategies mocks base method.
func (m *MockRepository) GetGrandStrategies(ctx context.Context) ([]api.GrandStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrandStrategies", ctx)
	ret0, _ := ret[0].([]api.GrandStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrandStrategies indicates an expected call of GetGrandStrategies.
func (mr *MockRepositoryMockRecorder) GetGrandStrategies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrandStrategies", reflect.TypeOf((*MockRepository)(nil).GetGrandStrategies), ctx)
}

// GetGrandStrategyByID mocks base method.
func (m *MockRepository) GetGrandStrategyByID(ctx context.Context, id string) (*api.GrandStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrandStrategyByID", ctx, id)
	ret0, _ := ret[0].(*api.GrandStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrandStrategyByID indicates an expected call of GetGrandStrategyByID.
func (mr *MockRepositoryMockRecorder) GetGrandStrategyByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrandStrategyByID", reflect.TypeOf((*MockRepository)(nil).GetGrandStrategyByID), ctx, id)
}

// GetUnitByID mocks base method.
func (m *MockRepository) GetUnitByID(ctx context.Context, id string) (*api.Unit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitByID", ctx, id)
	ret0, _ := ret[0].(*api.Unit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitByID indicates an expected call of GetUnitByID.
func (mr *MockRepositoryMockRecorder) GetUnitByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitByID", reflect.TypeOf((*MockRepository)(nil).GetUnitByID), ctx, id)
}

// GetUnits mocks base method.
func (m *MockRepository) GetUnits(ctx context.Context, params *api.GetUnitsParams) ([]api.Unit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnits", ctx, params)
	ret0, _ := ret[0].([]api.Unit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnits indicates an expected call of GetUnits.
func (mr *MockRepositoryMockRecorder) GetUnits(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnits", reflect.TypeOf((*MockRepository)(nil).GetUnits), ctx, params)
}

// GetWarscrollByID mocks base method.
func (m *MockRepository) GetWarscrollByID(ctx context.Context, id string) (*api.Warscroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarscrollByID", ctx, id)
	ret0, _ := ret[0].(*api.Warscroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarscrollByID indicates an expected call of GetWarscrollByID.
func (mr *MockRepositoryMockRecorder) GetWarscrollByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarscrollByID", reflect.TypeOf((*MockRepository)(nil).GetWarscrollByID), ctx, id)
}

// GetWarscrolls mocks base method.
func (m *MockRepository) GetWarscrolls(ctx context.Context, params *api.GetWarscrollsParams) ([]api.Warscroll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarscrolls", ctx, params)
	ret0, _ := ret[0].([]api.Warscroll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarscrolls indicates an expected call of GetWarscrolls.
func (mr *MockRepositoryMockRecorder) GetWarscrolls(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarscrolls", reflect.TypeOf((*MockRepository)(nil).GetWarscrolls), ctx, params)
}

// GetWeaponsForUnitByID mocks base method.
func (m *MockRepository) GetWeaponsForUnitByID(ctx context.Context, id string) (*api.WeaponsGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeaponsForUnitByID", ctx, id)
	ret0, _ := ret[0].(*api.WeaponsGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeaponsForUnitByID indicates an expected call of GetWeaponsForUnitByID.
func (mr *MockRepositoryMockRecorder) GetWeaponsForUnitByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeaponsForUnitByID", reflect.TypeOf((*MockRepository)(nil).GetWeaponsForUnitByID), ctx, id)
}

// Init mocks base method.
func (m *MockRepository) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockRepositoryMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockRepository)(nil).Init), ctx)
}

// Lock mocks base method.
func (m *MockRepository) Lock(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockRepositoryMockRecorder) Lock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockRepository)(nil).Lock), ctx)
}

// Migrate mocks base method.
func (m *MockRepository) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockRepositoryMockRecorder) Migrate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockRepository)(nil).Migrate), ctx)
}

// Rollback mocks base method.
func (m *MockRepository) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockRepositoryMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockRepository)(nil).Rollback), ctx)
}

// Seed mocks base method.
func (m *MockRepository) Seed(ctx context.Context, fsys fs.FS, names ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, fsys}
	for _, a := range names {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Seed", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Seed indicates an expected call of Seed.
func (mr *MockRepositoryMockRecorder) Seed(ctx, fsys interface{}, names ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, fsys}, names...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockRepository)(nil).Seed), varargs...)
}

// Unlock mocks base method.
func (m *MockRepository) Unlock(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockRepositoryMockRecorder) Unlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockRepository)(nil).Unlock), ctx)
}
