version: "3.7"


networks:
  default:
    name: warhammer
    driver: bridge

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  warhammer:
    container_name: warhammer 
    build:
      dockerfile: ./Dockerfile
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.warhammer.rule=Host(`warhammer.localhost`)"
      - "traefik.http.routers.warhammer.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.warhammer.loadbalancer.server.port=8080"
    environment:
      - WARHAMMER_SERVICE_NAME
      - WARHAMMER_SERVICE_PORT
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
    command: ["--migrate"]
    depends_on:
      otel_collector:
        condition: service_started

  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.76.1
    container_name: otel_collector
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otel_collector.rule=Host(`otel_collector.localhost`)"
      - "traefik.http.routers.otel_collector.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.otel_collector.loadbalancer.server.port=4318"
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped 
    command: [ "--config=/etc/otel-config.yaml", "--config=/etc/otel-observability.yaml" ]
    volumes:
        - ./config/otel-config.yaml:/etc/otel-config.yaml
        - ./config/otel-observability.yaml:/etc/otel-observability.yaml
    ports:
      - "4317"          # OTLP over gRPC receiver
      - "4318"          # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.localhost`)"
      - "traefik.http.routers.jaeger.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.jaeger.loadbalancer.server.port=${JAEGER_SERVICE_PORT}"
    restart: unless-stopped
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://${PROMETHEUS_ADDR}" 
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "${JAEGER_SERVICE_PORT}"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus

  prometheus:
    image: quay.io/prometheus/prometheus:v2.43.0
    container_name: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.docker.network=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=${PROMETHEUS_SERVICE_PORT}"
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "${PROMETHEUS_SERVICE_PORT}"