# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - go run ./cmd/aos

  up:
    desc: "Start the application with docker-compose"
    cmds:
      - docker-compose up --build --force-recreate --remove-orphans --detach

  gen:
    desc: "Generate code and documentation using go generate"
    cmds:
      - go generate ./... 

  lint:
    desc: "Run linter"
    cmds:
      - golangci-lint run ./...

  test:
    desc: "Run tests"
    cmds:
      - go test -v ./...