# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - go run ./cmd/warhammerd

  up:
    cmds:
      - docker-compose up --build --force-recreate --remove-orphans --detach

  gen:
    cmds:
      - go generate ./...
  
  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test -v ./...