// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AllegianceFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	Offset        *int    `json:"offset,omitempty"`
}

type UnitFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	GrandStrategy *string `json:"grandStrategy,omitempty"`
	Points        *int    `json:"points,omitempty"`
	Limit         *int    `json:"limit,omitempty"`
	Offset        *int    `json:"offset,omitempty"`
}

type WarscrollFilters struct {
	Name            *string `json:"name,omitempty"`
	Points          *int    `json:"points,omitempty"`
	BattlefieldRole *string `json:"battlefieldRole,omitempty"`
	Size            *string `json:"size,omitempty"`
	Notes           *string `json:"notes,omitempty"`
	Limit           *int    `json:"limit,omitempty"`
	Offset          *int    `json:"offset,omitempty"`
}
