// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AllegianceFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
}

type Size struct {
	Unit  string `json:"unit"`
	Value int    `json:"value"`
}

type UnitFilters struct {
	Name          *string `json:"name,omitempty"`
	GrandAlliance *string `json:"grandAlliance,omitempty"`
	GrandStrategy *string `json:"grandStrategy,omitempty"`
	Points        *int    `json:"points,omitempty"`
}

type WarscrollFilters struct {
	Name            *string `json:"name,omitempty"`
	Points          *int    `json:"points,omitempty"`
	BattlefieldRole *string `json:"battlefieldRole,omitempty"`
	Size            *string `json:"size,omitempty"`
	Notes           *string `json:"notes,omitempty"`
}
