apiVersion: 1

datasources:
- name: Prometheus
  access: proxy
  uid: prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  editable: true
 
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    maxLines: 5000
    derivedFields:
      - datasourceUid: jaeger
        matcherRegex: \"traceId\":\"([^"]+)\"
        name: traceId
        url: $${__value.raw}

- name: Jaeger
  type: jaeger
  uid: jaeger
  url: http://jaeger:16686
  access: proxy
  editable: true