apiVersion: 1

datasources:
- name: Prometheus
  access: proxy
  uid: prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  editable: true
 
- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  basicAuth: false
  editable: false
  uid: tempo
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus0

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
