# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
  loki:
    protocols:
      http:
    use_incoming_timestamp: true


processors:
  batch:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: container
    - action: insert
      key: loki.format
      value: raw

exporters:
  logging:
  otlp:
    endpoint: "${env:OTEL_EXPORTER_OTLP_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "${env:OTEL_EXPORTER_PROMETHEUS_ENDPOINT}"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  loki:
    endpoint: "${env:OTEL_EXPORTER_LOKI_ENDPOINT}}"

service:
  pipelines:
    logs:
      receivers: [otlp, loki]
      processors: [batch, attributes]
      exporters: [logging, loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
