global:
  evaluation_interval: 30s
  scrape_interval: 5s

scrape_configs:
- job_name: otel
  honor_labels: true
  static_configs:
  - targets: ['otel_collector:9464']

- job_name: otel-collector
  static_configs:
  - targets: ['otel_collector:8888']

- job_name: grafana
  static_configs:
  - targets: ['grafana:3000']

- job_name: loki
  static_configs:
  - targets: ['loki:3100']

- job_name: prometheus
  static_configs:
  - targets: ['prometheus:9090']  
  
- job_name: 'jaeger'
  static_configs:
  - targets: ['jaeger:14269']
