// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version v0.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/discord-gophers/goapi-gen/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

// Ability defines model for Ability.
type Ability struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Allegiance defines model for Allegiance.
type Allegiance struct {
	ID            *string `bun:"id,pk" json:"_id,omitempty"`
	Description   *string `json:"description,omitempty"`
	GrandAlliance *string `json:"grand_alliance,omitempty"`
	MortalRealm   *string `json:"mortal_realm,omitempty"`
	Name          string  `json:"name"`
}

// Army defines model for Army.
type Army struct {
	ID    *string `bun:"id,pk" json:"_id,omitempty"`
	Name  string  `json:"name"`
	Units []Unit  `json:"units,omitempty"`
}

// Attribute defines model for Attribute.
type Attribute struct {
	Name  *string `json:"name,omitempty"`
	Value *int64  `json:"value,omitempty"`
}

// DamageTable defines model for DamageTable.
type DamageTable struct {
	ID                 *string `bun:"id,pk" json:"_id,omitempty"`
	MinWoundsSuffered  *int64  `json:"min_wounds_suffered,omitempty"`
	Move               *Move   `json:"move,omitempty"`
	WoundTrackPosition *int64  `json:"wound_track_position,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GrandAlliance defines model for GrandAlliance.
type GrandAlliance struct {
	ID          *string `bun:",pk" json:"_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GrandStrategy defines model for GrandStrategy.
type GrandStrategy struct {
	ID          *string `bun:",pk" json:"_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Move defines model for Move.
type Move struct {
	Name  *string `json:"name,omitempty"`
	Value *int64  `json:"value,omitempty"`
}

// Size defines model for Size.
type Size struct {
	Unit  *string `json:"unit,omitempty"`
	Value *int64  `json:"value,omitempty"`
}

// Unit defines model for Unit.
type Unit struct {
	ID               *string       `bun:"id,pk" json:"_id,omitempty"`
	Abilities        []Ability     `json:"abilities,omitempty"`
	Bravery          *int64        `json:"bravery,omitempty"`
	CommandAbilities []Attribute   `json:"command_abilities,omitempty"`
	DamageTable      []DamageTable `json:"damage_table,omitempty"`
	Description      *string       `json:"description,omitempty"`
	GrandAlliance    *string       `json:"grand_alliance,omitempty"`
	Keywords         []string      `json:"keywords,omitempty"`
	Magic            []Attribute   `json:"magic,omitempty"`
	Models           *int64        `json:"models,omitempty"`
	Move             *Move         `json:"move,omitempty"`
	Name             string        `json:"name"`
	Points           *int64        `json:"points,omitempty"`
	Save             *int64        `json:"save,omitempty"`
	Size             *Size         `json:"size,omitempty"`
	Weapons          []Weapon      `json:"weapons,omitempty"`
	Wounds           *int64        `json:"wounds,omitempty"`
}

// Weapon defines model for Weapon.
type Weapon struct {
	ID      *string `bun:",pk" json:"_id,omitempty"`
	Attacks *int64  `json:"attacks,omitempty"`
	Damage  *int64  `json:"damage,omitempty"`
	Name    *string `json:"name,omitempty"`
	Range   *int64  `json:"range,omitempty"`
	Rend    *int64  `json:"rend,omitempty"`
	ToHit   *int64  `json:"to_hit,omitempty"`
	ToWound *int64  `json:"to_wound,omitempty"`
}

// GetAllegiancesParams defines parameters for GetAllegiances.
type GetAllegiancesParams struct {
	// name of allegiance to filter by
	Name *string `json:"name,omitempty"`

	// id of grand alliance to filter by
	GrandAlliance *string `json:"grand_alliance,omitempty"`
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// GetAllegiancesJSON200Response is a constructor method for a GetAllegiances response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAllegiancesJSON200Response(body []Allegiance) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetAllegiancesJSON404Response is a constructor method for a GetAllegiances response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAllegiancesJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetAllegianceByIDJSON200Response is a constructor method for a GetAllegianceByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAllegianceByIDJSON200Response(body Allegiance) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetAllegianceByIDJSON404Response is a constructor method for a GetAllegianceByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAllegianceByIDJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetArmiesJSON200Response is a constructor method for a GetArmies response.
// A *Response is returned with the configured status code and content type from the spec.
func GetArmiesJSON200Response(body []Army) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetArmiesJSON404Response is a constructor method for a GetArmies response.
// A *Response is returned with the configured status code and content type from the spec.
func GetArmiesJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetArmyByIDJSON200Response is a constructor method for a GetArmyByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetArmyByIDJSON200Response(body Army) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetArmyByIDJSON404Response is a constructor method for a GetArmyByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetArmyByIDJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetGrandAlliancesJSON200Response is a constructor method for a GetGrandAlliances response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandAlliancesJSON200Response(body []GrandAlliance) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetGrandAlliancesJSON404Response is a constructor method for a GetGrandAlliances response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandAlliancesJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetGrandAllianceByIDJSON200Response is a constructor method for a GetGrandAllianceByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandAllianceByIDJSON200Response(body GrandAlliance) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetGrandAllianceByIDJSON404Response is a constructor method for a GetGrandAllianceByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandAllianceByIDJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetGrandStrategiesJSON200Response is a constructor method for a GetGrandStrategies response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandStrategiesJSON200Response(body []GrandStrategy) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetGrandStrategiesJSON404Response is a constructor method for a GetGrandStrategies response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandStrategiesJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetGrandStrategyByIDJSON200Response is a constructor method for a GetGrandStrategyByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandStrategyByIDJSON200Response(body GrandStrategy) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetGrandStrategyByIDJSON404Response is a constructor method for a GetGrandStrategyByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetGrandStrategyByIDJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetUnitsJSON200Response is a constructor method for a GetUnits response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUnitsJSON200Response(body []Unit) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetUnitsJSON404Response is a constructor method for a GetUnits response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUnitsJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// GetUnitByIDJSON200Response is a constructor method for a GetUnitByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUnitByIDJSON200Response(body Unit) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetUnitByIDJSON404Response is a constructor method for a GetUnitByID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUnitByIDJSON404Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        404,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all allegiances
	// (GET /allegiances)
	GetAllegiances(w http.ResponseWriter, r *http.Request, params GetAllegiancesParams) *Response
	// Get allegiance by id
	// (GET /allegiances/{id})
	GetAllegianceByID(w http.ResponseWriter, r *http.Request, id string) *Response
	// Get all armies
	// (GET /armies)
	GetArmies(w http.ResponseWriter, r *http.Request) *Response
	// Get army by id
	// (GET /armies/{id})
	GetArmyByID(w http.ResponseWriter, r *http.Request, id string) *Response
	// Get all grand alliances
	// (GET /grand-alliances)
	GetGrandAlliances(w http.ResponseWriter, r *http.Request) *Response
	// Get grand alliance by id
	// (GET /grand-alliances/{id})
	GetGrandAllianceByID(w http.ResponseWriter, r *http.Request, id string) *Response
	// Get all grand strategies
	// (GET /grand-strategies)
	GetGrandStrategies(w http.ResponseWriter, r *http.Request) *Response
	// Get grand strategy by id
	// (GET /grand-strategies/{id})
	GetGrandStrategyByID(w http.ResponseWriter, r *http.Request, id string) *Response
	// Get all units
	// (GET /units)
	GetUnits(w http.ResponseWriter, r *http.Request) *Response
	// Get unit by id
	// (GET /units/{id})
	GetUnitByID(w http.ResponseWriter, r *http.Request, id string) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// GetAllegiances operation middleware
func (siw *ServerInterfaceWrapper) GetAllegiances(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllegiancesParams

	// ------------- Optional query parameter "name" -------------

	if err := runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name); err != nil {
		err = fmt.Errorf("invalid format for parameter name: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "name"})
		return
	}

	// ------------- Optional query parameter "grand_alliance" -------------

	if err := runtime.BindQueryParameter("form", true, false, "grand_alliance", r.URL.Query(), &params.GrandAlliance); err != nil {
		err = fmt.Errorf("invalid format for parameter grand_alliance: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "grand_alliance"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetAllegiances(w, r, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetAllegianceByID operation middleware
func (siw *ServerInterfaceWrapper) GetAllegianceByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetAllegianceByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetArmies operation middleware
func (siw *ServerInterfaceWrapper) GetArmies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetArmies(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetArmyByID operation middleware
func (siw *ServerInterfaceWrapper) GetArmyByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetArmyByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetGrandAlliances operation middleware
func (siw *ServerInterfaceWrapper) GetGrandAlliances(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetGrandAlliances(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetGrandAllianceByID operation middleware
func (siw *ServerInterfaceWrapper) GetGrandAllianceByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetGrandAllianceByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetGrandStrategies operation middleware
func (siw *ServerInterfaceWrapper) GetGrandStrategies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetGrandStrategies(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetGrandStrategyByID operation middleware
func (siw *ServerInterfaceWrapper) GetGrandStrategyByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetGrandStrategyByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetUnits operation middleware
func (siw *ServerInterfaceWrapper) GetUnits(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetUnits(w, r)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetUnitByID operation middleware
func (siw *ServerInterfaceWrapper) GetUnitByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetUnitByID(w, r, id)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:    "/",
		BaseRouter: chi.NewRouter(),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/allegiances", wrapper.GetAllegiances)
		r.Get("/allegiances/{id}", wrapper.GetAllegianceByID)
		r.Get("/armies", wrapper.GetArmies)
		r.Get("/armies/{id}", wrapper.GetArmyByID)
		r.Get("/grand-alliances", wrapper.GetGrandAlliances)
		r.Get("/grand-alliances/{id}", wrapper.GetGrandAllianceByID)
		r.Get("/grand-strategies", wrapper.GetGrandStrategies)
		r.Get("/grand-strategies/{id}", wrapper.GetGrandStrategyByID)
		r.Get("/units", wrapper.GetUnits)
		r.Get("/units/{id}", wrapper.GetUnitByID)
	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZ32/bNhD+VwRuj07stsFQ6M1DtyLYuhVIgz4UgXGWTjIbkVSPlFst8P8+kJL8S7RN",
	"Nz9gP8UxT3fH+77vjqIfWKJEqSRKo1n8wHQyQwHu43jKC25q+7EkVSIZjm4hRZ0QLw1X0v5r6hJZzLQh",
	"LnO2GDAJAj0Li0H3jZp+xcRY03FRYM5BJtgPM+Fp38uA/bjI1QX+MAQXBnJnOa0kixlPB+W9C3MowZxA",
	"phMoimXknolQZKCYEEIhjtwk4beKE6Ys/tJY3fk2TqJ+yi3vSGfAKskbZLlB4T78SpixmP0yXCE/bGEf",
	"3kru0mvdABHUR2zKGOLTynjA3JnfHIrKrWSKBBi7KWl+u2JL91wazJH8/HkHAnL8BNPiSQkkuJx8V5VM",
	"9URXWYZu4wEpWt7M8VCRP1ibxYC5CBNDkNxPSqV5x9efqsQfRIr6NUhU2qvum9f+1FFryANI7Xyu7H1M",
	"eG8VNl4T2OOQCRX2I0Xpsr4xBAbz+myy/tBS7kUEd8P/8wSzTeYZgt22bp9K1uAmWusmqB92M7DXEgds",
	"SjBHqgP7QqKEcEPn+BSWTdWTROr638R0DTDI43rT9Pl8/PS8x/q7onRzkz2r7cACcp48TV2ESrHQz9Cz",
	"d8qqVLw9QgVE1DDHUNNWcPuSc6K0AwWhVDKcWp+dva9+zfALFW5Qm2qDPVlXBWMguQ+teCOUQOOdIBPI",
	"YCeEMvTQYNRk1nS6MGOHzk92VfsVl5nqHeTZpxnXEdcRyGj88TrSJSY84wnY5ShTFEF0K1WW8YRDEX0G",
	"moEQSNE4x0hl0Q3PBZB91ObBjW1IbL/VHEk3sV9dji5HdneqRAklZzF7c/nqcsQGrAQzcygPYfmy4P7P",
	"0fQ38R5NBEURrds6r+T2cZ02NuON5RIIBBokzeIv2x4tGWzmK4+RUVHGC4MUTWtmy8li9q2yw6DjTvNn",
	"0L5OeYf7dhye2iiuuUZdcw2JtNWO98W8s6zUtkU0FXw9GjVnRGlQumJCWRYt5MOvupHryl9YX1690vVf",
	"JLbHC/v3L2t1Nbo6KpF98ZuDsCfUP8pEfzrl2DVdCQF2fHspYy3W+TZ84OniEOk6ekzriKf7Wfd7ff3u",
	"EPEaQmzSjtBUJDsmWGmsiOBirlqxoQqfkwyhHDhlzDcRa0AnwUP6S2PmA7lbeQGpkajPTWRNddZKHSAt",
	"EvUeUZGoj5CT9XVGQnIIny6iK2Qcom4WXXSz6LCKNqedV04bNwkvI6vNy4vz0td2RX2wHFbc1ilkp/Y2",
	"KhUuwv4h50zkuMWMk2WCF781KujmjosHS3TtgV00uFk3eSGRLu/qzlGkazX1QhMq0/aJ+oBMu1odK9Ol",
	"+zOT6YobJy7TLfwcF5a/2uzVZmPlAfy2XXh+Ge74weiU1ddUbVXmwzqzZrvVZUsQLirn63yk1OB7sniu",
	"IeOe1Ehzf/X/VgkUUbPOBqyigsVsZkwZD4eFXZspbeK3o7cj1r+b+UgqrRJ3EebxoOPhEJS+gJJfJkqw",
	"xd3i/wAAAP//Ml3oFFcfAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
