name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -o bin/warhammerd ./cmd/warhammerd

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2

    - name: Test
      run: |
        go test -v -race ./... -coverprofile cover.out

    - name: Coverage
      run: go tool cover -func cover.out